substitutions:
  <<: !include i18n.yaml
  devicename: "despensa"
  capitalized_name: "Despensa"
  devicecomment: "Luz automática da Despensa"
  board: d1_mini
  pin_rele: "GPIO5"
  pin_button: "GPIO4"
  pin_sensor: "GPIO16"
  apikey: !secret timed_door_light__apikey
  otakey: !secret timed_door_light__otakey
  wifi: "gz"
  wifipass: !secret timed_door_light__wifipass
  default_latitude: 21.5946°
  default_longitude: 47.2533°
  default_timezone: "America/Sao_Paulo"

<<: !include esphome_timed_door_light.yaml
