esphome:
  name: despensaautolight
  comment: Despensa - Luz Automática

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  port: 6053
  encryption:
    key: !secret despensaautolight_apikey
  reboot_timeout: 0s

ota:
  safe_mode: true
  password: !secret despensaautolight_otakey
  reboot_timeout: 0s
  id: my_ota

web_server:
  port: 80

wifi:
  ssid: !secret despensaautolight_wifiname
  password: !secret despensaautolight_wifipass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Despensa Fallback Hotspot"
    password: "12345678"

captive_portal:

time:
  - platform: sntp
    id: sntp_time
    timezone: "America/Sao_Paulo"
    servers: ["a.st1.ntp.br", "b.st1.ntp.br", "c.st1.ntp.br"]
    on_time:
      - seconds: "*"
        then:
          lambda: |-
            int tt = -1;

            /* incrementa, se ativado 'opened' */
            if (id(my__opened_lapse) >= 0){
              id(my__opened_lapse) += 1;
              tt = id(maxseconds).state - id(my__closed_lapse);
            }

            /* incrementa, se ativado 'closed' */
            if (id(my__closed_lapse) >= 0){
              id(my__closed_lapse) += 1;
              tt = id(minseconds).state - id(my__closed_lapse);
            }

            if (tt < 0){
              id(rele).turn_off();
              tt = 0;
            }

            unsigned short h, m, s; // Declare variables for seconds, hours, minutes, and seconds

            // Calculate hours, minutes, and remaining seconds
            h = (tt/3600);
            m = (tt -(3600*h))/60;
            s = (tt -(3600*h)-(m*60));

            char buf[19];// esperado 9 posições, mas colocado19 para evitar WARNs
            sprintf(buf, "%02d:%02d:%02d\n",h,m,s);
            id(remainingtime).state = buf;

globals:
  - id: my__opened_lapse
    type: int
    restore_value: no
    initial_value: "-10"

  - id: my__closed_lapse
    type: int
    restore_value: no
    initial_value: "-10"

number:
  - platform: template
    id: minseconds
    name: "Manter ligado por no mínimo (s)"
    min_value: 10
    max_value: 600
    step: 1
    initial_value: 30
    optimistic: true
    restore_value: true

  - platform: template
    id: maxseconds
    name: "Manter ligado por no mánimo (s)"
    min_value: 30
    max_value: 1800
    step: 1
    initial_value: 600
    optimistic: true
    restore_value: true

button:
  - platform: restart
    name: "Restart"

switch:
  - platform: gpio
    name: "Iluminação (0)"
    id: rele
    pin:
      number: 0
      inverted: true

    disabled_by_default: true
    restore_mode: RESTORE_DEFAULT_OFF

    on_turn_on:
      lambda: |-
        id(my__opened_lapse) = 0;
        id(my__closed_lapse) = -10;

    on_turn_off:
      lambda: |-
        id(my__opened_lapse) = -10;
        id(my__closed_lapse) = -10;

text_sensor:
  - platform: version
    id: remainingtime
    name: "Tempo para desligar"

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: 13
      mode:
        input: true
        pullup: true
    name: "Porta Aberta (13) (gnd)"
    filters:
      - delayed_on_off: 400ms
    on_state:
      lambda: |-
        if (x){
          id(rele).turn_on();
        }else{
          id(my__opened_lapse) = -10;
          id(my__closed_lapse) = 0;
        }
